version: '3.7'

services:

  report-back:
    container_name: report-back
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: 'gabustoledo/report-back'
    volumes:
      - '.:/app'
      - '/app/node_modules' 
    ports:
      - 8080:8080
